// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	Key       uuid.UUID        `json:"key"`
	UserID    uuid.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Click struct {
	ID        int32            `json:"id"`
	ShortID   pgtype.Text      `json:"short_id"`
	IpAddress pgtype.Text      `json:"ip_address"`
	UserAgent pgtype.Text      `json:"user_agent"`
	ClickedAt pgtype.Timestamp `json:"clicked_at"`
}

type Url struct {
	ShortID    string           `json:"short_id"`
	LongUrl    string           `json:"long_url"`
	UserID     pgtype.UUID      `json:"user_id"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
	ClickLimit pgtype.Int4      `json:"click_limit"`
}

type User struct {
	UserID    uuid.UUID        `json:"user_id"`
	Username  string           `json:"username"`
	Email     string           `json:"email"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
