// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateURL(ctx context.Context, arg CreateURLParams) (Url, error)
	// queries.sql
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error
	DeleteURL(ctx context.Context, arg DeleteURLParams) error
	GetAPIKey(ctx context.Context, key uuid.UUID) (ApiKey, error)
	GetTotalClicks(ctx context.Context) (int64, error)
	GetTotalURLs(ctx context.Context) (int64, error)
	GetTotalUsers(ctx context.Context) (int64, error)
	GetURL(ctx context.Context, shortID string) (Url, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, userID uuid.UUID) (User, error)
	ListClicks(ctx context.Context, shortID pgtype.Text) ([]Click, error)
	ListUserAPIKeys(ctx context.Context, userID uuid.UUID) ([]ApiKey, error)
	ListUserURLs(ctx context.Context, userID pgtype.UUID) ([]Url, error)
	LogClick(ctx context.Context, arg LogClickParams) error
	UpdateURL(ctx context.Context, arg UpdateURLParams) (Url, error)
}

var _ Querier = (*Queries)(nil)
