version: '3.8'

# Production overrides for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:
  postgres:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    ports: []  # Remove port exposure in production
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  redis:
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data_prod:/data
    ports: []  # Remove port exposure in production
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  app:
    environment:
      POSTGRES_DSN: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/urlshortener?sslmode=disable
      REDIS_PASS: ${REDIS_PASSWORD}
      GIN_MODE: release
    ports: []  # Remove direct port exposure, use nginx
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  nginx:
    ports:
      - "80:80"
      - "443:443"
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

volumes:
  postgres_data_prod:
    driver: local
  redis_data_prod:
    driver: local
